# Generated by Django 5.2.5 on 2026-08-11 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='liqpay', max_length=32)),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('pending', 'Очікує'), ('success', 'Успішно'), ('failure', 'Помилка'), ('sandbox', 'Sandbox / bypass')], db_index=True, default='created', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
