# Generated by Django 5.2.5 on 2026-08-28 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='UAH', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Зовнішній ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Ключ ідемпотентності'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='ID замовлення'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='liqpay', max_length=32, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сирий payload'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('pending', 'Очікує'), ('success', 'Успішно'), ('failure', 'Помилка'), ('sandbox', 'Sandbox / bypass')], db_index=True, default='created', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
