# Generated by Django 5.2.5 on 2026-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('locale', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Русский')], default='uk', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Інфосторінка',
                'verbose_name_plural': 'Інфосторінки',
                'ordering': ['slug', 'locale'],
                'unique_together': {('slug', 'locale')},
            },
        ),
    ]
