# Generated by Django 5.2.5 on 2026-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('text_uk', models.TextField()),
                ('text_ru', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Картка «Про нас»',
                'verbose_name_plural': 'Картки «Про нас»',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uk', models.CharField(max_length=255)),
                ('question_ru', models.CharField(blank=True, max_length=255)),
                ('answer_uk', models.TextField()),
                ('answer_ru', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ пункт',
                'verbose_name_plural': 'FAQ пункти',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('body_uk', models.TextField(blank=True, help_text='HTML (TinyMCE)')),
                ('body_ru', models.TextField(blank=True, help_text='HTML (TinyMCE)')),
                ('updated_label_uk', models.CharField(blank=True, max_length=255)),
                ('updated_label_ru', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Юридична сторінка',
                'verbose_name_plural': 'Юридичні сторінки',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterModelOptions(
            name='infopage',
            options={'ordering': ['slug', 'locale'], 'verbose_name': 'Інфосторінка (legacy)', 'verbose_name_plural': 'Інфосторінки (legacy)'},
        ),
    ]
