# Generated by Django 5.2.5 on 2026-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cms_site_blocks_legal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Пункт FAQ', 'verbose_name_plural': 'Пункти FAQ'},
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Текст (російською)'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='text_uk',
            field=models.TextField(verbose_name='Текст (українською)'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (російською)'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (українською)'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_ru',
            field=models.TextField(blank=True, verbose_name='Відповідь (російською)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_uk',
            field=models.TextField(verbose_name='Відповідь (українською)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Питання (російською)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_uk',
            field=models.CharField(max_length=255, verbose_name='Питання (українською)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='locale',
            field=models.CharField(choices=[('uk', 'Українська'), ('ru', 'Русский')], default='uk', max_length=5, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='body_ru',
            field=models.TextField(blank=True, help_text='HTML (редактор TinyMCE)', verbose_name='Текст (російською)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='body_uk',
            field=models.TextField(blank=True, help_text='HTML (редактор TinyMCE)', verbose_name='Текст (українською)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (російською)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (українською)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='updated_label_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мітка оновлення (російською)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='updated_label_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мітка оновлення (українською)'),
        ),
    ]
