# Generated by Django 5.2.5 on 2026-08-11 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Очікує'), ('paid', 'Оплачено')], db_index=True, default='unpaid', max_length=16)),
                ('current_level', models.PositiveSmallIntegerField(default=0)),
                ('locale', models.CharField(default='uk', max_length=5)),
                ('consent_terms_at', models.DateTimeField(blank=True, null=True)),
                ('consent_age18_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль гравця',
                'verbose_name_plural': 'Гравці',
            },
        ),
    ]
