# Generated by Django 5.2.5 on 2026-08-28 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='consent_age18_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Підтвердження 18+'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='consent_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Згода з угодою'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Поточний рівень'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(default='uk', max_length=5, verbose_name='Мова інтерфейсу'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Очікує'), ('paid', 'Оплачено')], db_index=True, default='unpaid', max_length=16, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
