# Generated by Django 5.2.5 on 2026-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('body_uk', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, upload_to='quest/')),
                ('media_type', models.CharField(blank=True, choices=[('', 'Без медіа'), ('pdf', 'PDF'), ('png', 'Зображення'), ('mp3', 'Аудіо'), ('mp4', 'Відео')], default='', max_length=8)),
                ('keyword_normalized', models.CharField(help_text='Одне ключове слово для uk і ru (зберігається нормалізованим).', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кімната квесту',
                'verbose_name_plural': 'Кімнати квесту',
                'ordering': ['order'],
            },
        ),
    ]
