# Generated by Django 5.2.5 on 2026-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questroom',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Текст завдання (російською)'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='body_uk',
            field=models.TextField(blank=True, verbose_name='Текст завдання (українською)'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='keyword_normalized',
            field=models.CharField(help_text='Одне слово для української та російської. Зберігається нормалізованим.', max_length=128, verbose_name='Ключове слово'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='media_file',
            field=models.FileField(blank=True, upload_to='quest/', verbose_name='Файл медіа'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='media_type',
            field=models.CharField(blank=True, choices=[('', 'Без медіа'), ('pdf', 'PDF'), ('png', 'Зображення'), ('mp3', 'Аудіо'), ('mp4', 'Відео')], default='', max_length=8, verbose_name='Тип медіа'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер кімнати'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (російською)'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Назва (українською)'),
        ),
        migrations.AlterField(
            model_name='questroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
