# Generated by Django 5.2.5 on 2026-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Квест-марафон', max_length=128)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('apple_touch_icon', models.ImageField(blank=True, upload_to='branding/')),
                ('phone', models.CharField(blank=True, default='+38 (093) 000-11-22', max_length=32)),
                ('email', models.EmailField(blank=True, default='info@example.com', max_length=254)),
                ('address_uk', models.CharField(blank=True, default='вул. Хрещатик, 1, м. Київ', max_length=255)),
                ('address_ru', models.CharField(blank=True, default='ул. Крещатик, 1, г. Киев', max_length=255)),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/kvestmarafon')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/kvestmarafon/')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/kvestmarafon')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('faq', 'FAQ'), ('contacts', 'Контакти'), ('site', 'Сайт')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання')], default='text', max_length=16)),
                ('text_uk', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('link_url', models.CharField(blank=True, max_length=512)),
                ('link_label', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — заголовки',
                'verbose_name_plural': 'Про нас — заголовки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти — тексти',
                'verbose_name_plural': 'Контакти — тексти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='FaqPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ — заголовки',
                'verbose_name_plural': 'FAQ — заголовки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeIntroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Intro',
                'verbose_name_plural': 'Головна — Intro',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал',
                'verbose_name_plural': 'Підвал',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
