# Generated by Django 5.2.5 on 2026-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cms_site_blocks_legal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagesettings',
            options={'verbose_name': 'Про нас', 'verbose_name_plural': 'Про нас'},
        ),
        migrations.AlterModelOptions(
            name='contactspagesettings',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='faqpagesettings',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='homeintrosettings',
            options={'verbose_name': 'Головна', 'verbose_name_plural': 'Головна'},
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання')], default='text', max_length=16, verbose_name='Тип контенту'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='key',
            field=models.CharField(max_length=64, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='label',
            field=models.CharField(blank=True, max_length=128, verbose_name='Підпис'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='link_label',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст посилання'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='link_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='URL посилання'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('faq', 'FAQ'), ('contacts', 'Контакти'), ('site', 'Сайт')], max_length=32, verbose_name='Сторінка'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Текст (російською)'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='text_uk',
            field=models.TextField(blank=True, verbose_name='Текст (українською)'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, default='ул. Крещатик, 1, г. Киев', max_length=255, verbose_name='Адреса (російською)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, default='вул. Хрещатик, 1, м. Київ', max_length=255, verbose_name='Адреса (українською)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='Іконка Apple Touch'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/kvestmarafon', verbose_name='Посилання Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/kvestmarafon/', verbose_name='Посилання Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+38 (093) 000-11-22', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Квест-марафон', max_length=128, verbose_name='Назва сайту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, default='https://t.me/kvestmarafon', verbose_name='Посилання Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='participants_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість учасників'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
