# Generated by Django 5.2.5 on 2026-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uk_field_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='file',
            field=models.FileField(blank=True, upload_to='blocks/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('file', 'Файл'), ('url', 'Посилання')], default='text', max_length=16, verbose_name='Тип контенту'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('faq', 'FAQ'), ('contacts', 'Контакти'), ('rating', 'Рейтинг'), ('site', 'Сайт')], max_length=32, verbose_name='Сторінка'),
        ),
    ]
