# Generated by Django 5.2.5 on 2026-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='body',
            field=models.TextField(verbose_name='Текст листа'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість отримувачів'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Надіслано'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
    ]
